## Create APB

Create an APB project using the APB CLI:

[source,shell,role=copypaste]
```
$ cd ~
$ apb init mysql-digital-ocean-apb --bindable
```

Take a look inside the `mysql-digital-ocean-apb` directory and review `apb.yml`

[source,shell,role=copypaste]
```
$ cd mysql-digital-ocean-apb
$ cat apb.yml
```

Define the parameters for the MySQL APB by replacing it with the following:

[source,shell,role=copypaste]
```
$ cat <<'EOF' > apb.yml
_params: &_params
  - name: service_name
    title: Database service name
    description: The name of the service. Used to name droplet and OpenShit service
    type: string
    default: domysql
    pattern: "^[a-zA-Z0-9]+[a-zA-Z0-9]*[a-zA-Z0-9]+$"
    required: true
  - name: region
    title: Target region
    description: Region where VM will be provisioned
    type: enum
    enum: [nyc1,nyc2,nyc3,sfo1,sfo2,ams2,ams3,sgp1,lon1,fra1,tor1,blr1]
    default: sfo1
    reguired: true
    display_type: select
  - name: mysql_database
    title: Database name
    description: The name of the MySQL database
    type: string
    default: catalog
    pattern: "^[a-zA-Z0-9_]*[a-zA-Z_]+[a-zA-Z0-9_]*$"
    required: true
  - name: mysql_user
    title: Database username 
    description: Username that will be used to connect to MySQL
    type: string
    default: admin
    pattern: "^[a-zA-Z0-9_]*[a-zA-Z_]+[a-zA-Z0-9_]*$"
    required: true
  - name: mysql_password
    title: Database user password
    description: Password to connect to MySQL
    type: string
    required: true
    display_type: password
version: 1.0
name: mysql-digital-ocean-apb
description: MySQL database from Digital Ocean
bindable: true
async: optional
tags:
- database
- mysql
metadata:
  displayName: "Digital Ocean MySQL (APB)"
  longDescription: "MySQL 5.7 running on CentOs 7.4 in Digital Ocean"
  console.openshift.io/iconClass: icon-mysql-database
  providerDisplayName: "Red Hat, Inc."
plans:
  - name: 512mb
    description: Small droplet with MySQL
    free: true
    metadata:
      displayName: Default (512MB)
      longDescription: This plan provides small (512MB) droplet from Digital Ocean with MySQL
      cost: $0.00
    parameters: *_params
  - name: 2gb
    description: Small droplet with MySQL
    free: true
    metadata:
      displayName: Medium (2GB)
      longDescription: This plan provides medium (2GB) droplet from Digital Ocean with MySQL
      cost: $10.00 monthly
    parameters: *_params
  - name: 4gb
    description: Small droplet with MySQL
    free: true
    metadata:
      displayName: Large (4GB)
      longDescription: This plan provides large (4GB) droplet from Digital Ocean with MySQL
      cost: $40.00 monthly
    parameters: *_params
EOF
```

Explain how playbooks work in APBs and review the existing playbooks in `playbooks/`

Copy the existing roles and playbooks to use the Digital Oceal ansible modules avaialble 
on Ansible Galaxy:

[source,shell,role=copypaste]
```
$ \cp -rf ~/support/mysql-digital-ocean-apb/{playbooks,roles} .     # \ is to disable the 'cp -i' alias
```

Explain the APB process (build docker image, push ,etc). Although APB CLI generates a Dockerfile since
you need some extra python libraries, replace it with this one:

[source,shell,role=copypaste]
```
$ cat <<'EOF' > Dockerfile
FROM openshift3/apb-base

LABEL "com.redhat.apb.spec"=\

RUN yum-config-manager --disable rhel-7-server-htb-rpms && yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum -y update && yum -y install python git python-pip python-requests python-setuptools python-wheel && yum clean all
RUN pip install --upgrade pip --user apb --cache-dir /tmp && pip install --user apb 'dopy>=0.3.7,<=0.3.7' --cache-dir /tmp        
RUN chown -R apb:0 /opt/apb && chmod -R g=u /opt/apb /etc/passwd

COPY playbooks /opt/apb/actions
COPY roles /opt/apb/actions/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
ENV ANSIBLE_HOST_KEY_CHECKING false

EOF
```

Now you are done with authoring the APB. Prepare it for distribution:

[source,shell,role=copypaste]
```
$ apb prepare
```
`
Review Dockerfile and note LABEL

Build the APB container image:

[source,shell,role=copypaste]
```
$ sudo apb build
```

Now you should add it to the service catalog. You have to log in as admin first since this is admin thing to do:

[source,shell,role=copypaste]
```
$ oc login -u admin -p openshift
$ sudo apb push --registry-route {{ OPENSHIFT_REGISTRY }}
```

Log back in as your own user for rest of the labs

[source,shell,role=copypaste]
```
$ oc login -u {{ OPENSHIFT_USER }}
```

Go to the OpenShift Web Console and inside the STAGE project and in the _Search Catalog_ field search for 
_Digital Ocean_  and click on **Digital Ocean MySQL* to provision it. We hav already added a secret to keep Digital Ocean API authentications. 
You will read what that means in the next paragraph!

Connect it with your app now.

[source,shell,role=copypaste]
```
$ cat <<'EOF' > /tmp/application.properties
spring.datasource.url=jdbc:mysql://${APB_DB_SERVICE_NAME}:3306/${APB_DB_NAME}?useSSL=false
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=${APB_DB_USER}
spring.datasource.password=${APB_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
EOF
```

Delete old configmap

[source,shell,role=copypaste]
```
$ oc delete configmap catalog -n stage
```

Create new configmap and redeploy catalog

[source,shell,role=copypaste]
```
$ oc create configmap catalog --from-file=/tmp/application.properties -n stage
$ oc rollout latest catalog -n stage
```
